networks:
  bitswan_network:
    external: true
services:
  deployment-management-backend-d86b-dev:
    container_name: deployment-management-backend-d86b-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: 5e6c4b59ff72c4303b6fdaab4ae2846ed9b43643
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:02.956477Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: backend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.stage: dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-d86b-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/5e6c4b59ff72c4303b6fdaab4ae2846ed9b43643:/app/
  deployment-management-backend-d86b-live-dev:
    container_name: deployment-management-backend-d86b-live-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:03.181934Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: backend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/backend:/app/
  deployment-management-backend-d86b-production:
    container_name: deployment-management-backend-d86b-production
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres
    - /gitops/secrets/minio
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-d86b-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: 3cf337ac96d92e9d302a56649f0b5fd50d0b17a4
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:02.749629Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: backend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.stage: production
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-d86b-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/3cf337ac96d92e9d302a56649f0b5fd50d0b17a4:/app/
  deployment-management-backend-d86b-staging:
    container_name: deployment-management-backend-d86b-staging
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-staging
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: 5e6c4b59ff72c4303b6fdaab4ae2846ed9b43643
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:03.393046Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: backend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.stage: staging
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-d86b-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/5e6c4b59ff72c4303b6fdaab4ae2846ed9b43643:/app/
  deployment-management-backend-f4a9-live-dev:
    container_name: deployment-management-backend-f4a9-live-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:03.602686Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: wt-tims-dev-tree-deployment-management
      gitops.deployment_id: backend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-f4a9-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/backend:/app/
  deployment-management-external-frontend-d86b-dev:
    container_name: deployment-management-external-frontend-d86b-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: 748e431259b9b0a508f1af623b54e8b8ef130675
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:04.259042Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: external-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: external-frontend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.stage: dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-d86b-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/748e431259b9b0a508f1af623b54e8b8ef130675:/app/
  deployment-management-external-frontend-d86b-live-dev:
    container_name: deployment-management-external-frontend-d86b-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:04.468152Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: external-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: external-frontend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/external-frontend:/app/
  deployment-management-external-frontend-d86b-production:
    container_name: deployment-management-external-frontend-d86b-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-d86b-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: f2c7edfe4b9dc7d3678af56d7c61c0d90e068818
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:04.061235Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: external-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: external-frontend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.stage: production
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-d86b-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/f2c7edfe4b9dc7d3678af56d7c61c0d90e068818:/app/
  deployment-management-external-frontend-d86b-staging:
    container_name: deployment-management-external-frontend-d86b-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: 748e431259b9b0a508f1af623b54e8b8ef130675
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:04.651445Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: external-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: external-frontend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.stage: staging
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-d86b-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/748e431259b9b0a508f1af623b54e8b8ef130675:/app/
  deployment-management-external-frontend-f4a9-live-dev:
    container_name: deployment-management-external-frontend-f4a9-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:04.881932Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: external-frontend
      gitops.certs.enabled: 'true'
      gitops.context: wt-tims-dev-tree-deployment-management
      gitops.deployment_id: external-frontend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-f4a9-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/external-frontend:/app/
  deployment-management-internal-frontend-d86b-dev:
    container_name: deployment-management-internal-frontend-d86b-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: b586d4be65e50ac8feb075f14121e5f0fbd785f6
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:05.647024Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: WtCqpAiMbWrhfSVXh1HwrqsELcbLuDeb
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-d86b-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: internal-frontend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-d86b-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/b586d4be65e50ac8feb075f14121e5f0fbd785f6:/app/
  deployment-management-internal-frontend-d86b-live-dev:
    container_name: deployment-management-internal-frontend-d86b-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:06.185589Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: PXkIT9YVH3AdCzbBr19WaAmAci3EgdwA
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: internal-frontend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/internal-frontend:/app/
  deployment-management-internal-frontend-d86b-production:
    container_name: deployment-management-internal-frontend-d86b-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-d86b-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: 8362aa30e72408b2442d291510ba6dad177cd7de
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:05.116873Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-client
      OAUTH2_PROXY_CLIENT_SECRET: 4vjcz8yyxhlPd8iQlYe0TO7zKEnWYoW1
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-d86b-production.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: internal-frontend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: production
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-d86b-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/8362aa30e72408b2442d291510ba6dad177cd7de:/app/
  deployment-management-internal-frontend-d86b-staging:
    container_name: deployment-management-internal-frontend-d86b-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: b586d4be65e50ac8feb075f14121e5f0fbd785f6
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:06.723988Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-staging-client
      OAUTH2_PROXY_CLIENT_SECRET: r9U9EaAEaifTw4KzPs5J7mrztMrNXZBK
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-d86b-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/deployment-management-deployment-management-internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: deployment-management
      gitops.deployment_id: internal-frontend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: staging
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-d86b-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/b586d4be65e50ac8feb075f14121e5f0fbd785f6:/app/
  deployment-management-internal-frontend-f4a9-live-dev:
    container_name: deployment-management-internal-frontend-f4a9-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-20T18:51:07.222410Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-f4a9-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-wt-tims-dev-tree-deployment-management-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: wYGSaoMZxALoMDJL5fjaxZnfdOojBJYH
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-f4a9-live-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: wt-tims-dev-tree-deployment-management
      gitops.deployment_id: internal-frontend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: live-dev
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-f4a9-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/internal-frontend:/app/
  minio:
    command: server /data --console-address :9001
    container_name: deployment-management__minio
    env_file:
    - /gitops/secrets/minio
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-data-data:/data
  minio-dev:
    command: server /data --console-address :9001
    container_name: deployment-management__minio-dev
    env_file:
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio-dev.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-dev-data-data:/data
  minio-staging:
    command: server /data --console-address :9001
    container_name: deployment-management__minio-staging
    env_file:
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio-staging.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-staging-data-data:/data
  postgres:
    container_name: deployment-management__postgres
    env_file:
    - /gitops/secrets/postgres
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-data-data:/var/lib/postgresql/data
  postgres-dev:
    container_name: deployment-management__postgres-dev
    env_file:
    - /gitops/secrets/postgres-dev
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-dev-data-data:/var/lib/postgresql/data
  postgres-dev-pgadmin:
    container_name: deployment-management__postgres-dev-pgadmin
    env_file:
    - /gitops/secrets/postgres-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres-dev.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-pgadmin:
    container_name: deployment-management__postgres-pgadmin
    env_file:
    - /gitops/secrets/postgres
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-staging:
    container_name: deployment-management__postgres-staging
    env_file:
    - /gitops/secrets/postgres-staging
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-staging-data-data:/var/lib/postgresql/data
  postgres-staging-pgadmin:
    container_name: deployment-management__postgres-staging-pgadmin
    env_file:
    - /gitops/secrets/postgres-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres-staging.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
version: '3'
volumes:
  deployment-management-minio-data-data: null
  deployment-management-minio-dev-data-data: null
  deployment-management-minio-staging-data-data: null
  deployment-management-postgres-data-data: null
  deployment-management-postgres-dev-data-data: null
  deployment-management-postgres-staging-data-data: null
