networks:
  bitswan_network:
    external: true
services:
  backend-d86b-live-dev:
    container_name: deployment-management__backend-d86b-live-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:52.554732Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/backend:/app/
  backend-deployment-manag-dev:
    container_name: deployment-management__backend-deployment-manag-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-deployment-manag-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: 3cf337ac96d92e9d302a56649f0b5fd50d0b17a4
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:52.317622Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-deployment-manag-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/3cf337ac96d92e9d302a56649f0b5fd50d0b17a4:/app/
  backend-deployment-manag-production:
    container_name: deployment-management__backend-deployment-manag-production
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres
    - /gitops/secrets/minio
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-deployment-manag-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: ea6fea19c4b4d14e63dc994d2301023f7830b463
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:52.088636Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-deployment-manag-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/ea6fea19c4b4d14e63dc994d2301023f7830b463:/app/
  backend-deployment-manag-staging:
    container_name: deployment-management__backend-deployment-manag-staging
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-staging
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-deployment-manag-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: backend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: ea6fea19c4b4d14e63dc994d2301023f7830b463
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:52.787963Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-deployment-manag-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/ea6fea19c4b4d14e63dc994d2301023f7830b463:/app/
  backend-dev-dev:
    container_name: deployment-management__backend-dev-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-dev-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: backend-dev
      BITSWAN_DEPLOY_CHECKSUM: c51f60505bbd1bbadb702f432a35d80ab651e2fc
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:53.010114Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-dev-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/c51f60505bbd1bbadb702f432a35d80ab651e2fc:/app/
  backend-live-dev-live-dev:
    container_name: deployment-management__backend-live-dev-live-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-live-dev-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:53.260313Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-live-dev-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/backend:/app/
  backend-production:
    container_name: deployment-management__backend-production
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres
    - /gitops/secrets/minio
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: backend
      BITSWAN_DEPLOY_CHECKSUM: c51f60505bbd1bbadb702f432a35d80ab651e2fc
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:51.782502Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/c51f60505bbd1bbadb702f432a35d80ab651e2fc:/app/
  backend-staging-staging:
    container_name: deployment-management__backend-staging-staging
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-staging
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-staging-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: backend-staging
      BITSWAN_DEPLOY_CHECKSUM: c51f60505bbd1bbadb702f432a35d80ab651e2fc
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:53.509054Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-staging
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-staging-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/c51f60505bbd1bbadb702f432a35d80ab651e2fc:/app/
  backend-wt-tims-dev-tree-live-dev:
    container_name: deployment-management__backend-wt-tims-dev-tree-live-dev
    env_file:
    - /gitops/secrets/dockerhub
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-backend-wt-tims-dev-tree-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:53.769507Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: backend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-backend-wt-tims-dev-tree-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/backend:/app/
  external-frontend-d86b-live-dev:
    container_name: deployment-management__external-frontend-d86b-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:54.725039Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/external-frontend:/app/
  external-frontend-deploy-dev:
    container_name: deployment-management__external-frontend-deploy-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-deploy-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: f2c7edfe4b9dc7d3678af56d7c61c0d90e068818
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:54.477477Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-deploy-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/f2c7edfe4b9dc7d3678af56d7c61c0d90e068818:/app/
  external-frontend-deploy-production:
    container_name: deployment-management__external-frontend-deploy-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-deploy-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: 5c18b6e4bc3272375e5a4c04243c95a85522cd77
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:54.244242Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-deploy-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/5c18b6e4bc3272375e5a4c04243c95a85522cd77:/app/
  external-frontend-deploy-staging:
    container_name: deployment-management__external-frontend-deploy-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-deploy-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: external-frontend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: 5c18b6e4bc3272375e5a4c04243c95a85522cd77
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:54.973079Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-deploy-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/5c18b6e4bc3272375e5a4c04243c95a85522cd77:/app/
  external-frontend-dev-dev:
    container_name: deployment-management__external-frontend-dev-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-dev-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-dev
      BITSWAN_DEPLOY_CHECKSUM: 0d00970e7026580366954fd12c2ea25d03992e36
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:55.216578Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-dev-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/0d00970e7026580366954fd12c2ea25d03992e36:/app/
  external-frontend-live-d-live-dev:
    container_name: deployment-management__external-frontend-live-d-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-live-d-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:55.437679Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-live-d-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/external-frontend:/app/
  external-frontend-production:
    container_name: deployment-management__external-frontend-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: external-frontend
      BITSWAN_DEPLOY_CHECKSUM: 0d00970e7026580366954fd12c2ea25d03992e36
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:54.007320Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/0d00970e7026580366954fd12c2ea25d03992e36:/app/
  external-frontend-stagin-staging:
    container_name: deployment-management__external-frontend-stagin-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-stagin-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: external-frontend-staging
      BITSWAN_DEPLOY_CHECKSUM: 0d00970e7026580366954fd12c2ea25d03992e36
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:55.646260Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-staging
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-stagin-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/0d00970e7026580366954fd12c2ea25d03992e36:/app/
  external-frontend-wt-tim-live-dev:
    container_name: deployment-management__external-frontend-wt-tim-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-external-frontend-wt-tim-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: external-frontend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:55.858317Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/external-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: external-frontend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-external-frontend-wt-tim-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/external-frontend:/app/
  internal-frontend-d86b-live-dev:
    container_name: deployment-management__internal-frontend-d86b-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:57.650824Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-d86b-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: PXkIT9YVH3AdCzbBr19WaAmAci3EgdwA
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-d86b-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/internal-frontend:/app/
  internal-frontend-deploy-dev:
    container_name: deployment-management__internal-frontend-deploy-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-deploy-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-dev
      BITSWAN_DEPLOY_CHECKSUM: 8362aa30e72408b2442d291510ba6dad177cd7de
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:57.164187Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: WtCqpAiMbWrhfSVXh1HwrqsELcbLuDeb
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-deploy-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-deployment-management-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-deploy-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/8362aa30e72408b2442d291510ba6dad177cd7de:/app/
  internal-frontend-deploy-production:
    container_name: deployment-management__internal-frontend-deploy-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-deploy-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management
      BITSWAN_DEPLOY_CHECKSUM: 761f7d00b96d95319df33d16ee8f16e225e90848
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:56.636677Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o.
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-client
      OAUTH2_PROXY_CLIENT_SECRET: 4vjcz8yyxhlPd8iQlYe0TO7zKEnWYoW1
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-deploy-production.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-deployment-management
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-deploy-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/761f7d00b96d95319df33d16ee8f16e225e90848:/app/
  internal-frontend-deploy-staging:
    container_name: deployment-management__internal-frontend-deploy-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-deploy-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: internal-frontend-deployment-management-staging
      BITSWAN_DEPLOY_CHECKSUM: 761f7d00b96d95319df33d16ee8f16e225e90848
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:58.177489Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o.
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-deployment-management-staging-client
      OAUTH2_PROXY_CLIENT_SECRET: r9U9EaAEaifTw4KzPs5J7mrztMrNXZBK
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-deploy-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-deployment-management-staging
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-deploy-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/761f7d00b96d95319df33d16ee8f16e225e90848:/app/
  internal-frontend-dev-dev:
    container_name: deployment-management__internal-frontend-dev-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-dev-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-dev
      BITSWAN_DEPLOY_CHECKSUM: b79a86623d2cb8120f15d30c2f302db2b3c76521
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:58.680078Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./WingsData s.r.o.
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: ofofPqh1m7NZMSWMVdV9xJGuhKPBF2nw
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-dev-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-dev-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/b79a86623d2cb8120f15d30c2f302db2b3c76521:/app/
  internal-frontend-live-d-live-dev:
    container_name: deployment-management__internal-frontend-live-d-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-live-d-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:59.167789Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: 4ryGgRFd2nrBFKPda3hWVriZWNFVCKot
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-live-d-live-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-live-d-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/deployment-management/internal-frontend:/app/
  internal-frontend-production:
    container_name: deployment-management__internal-frontend-production
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-production.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_ID: internal-frontend
      BITSWAN_DEPLOY_CHECKSUM: b79a86623d2cb8120f15d30c2f302db2b3c76521
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:56.100438Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./WingsData s.r.o.
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-client
      OAUTH2_PROXY_CLIENT_SECRET: eM7nYE5LIrVcY1V8tGEm4hecqYtrYavk
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-production.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-production.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/b79a86623d2cb8120f15d30c2f302db2b3c76521:/app/
  internal-frontend-stagin-staging:
    container_name: deployment-management__internal-frontend-stagin-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-stagin-staging.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: staging
      BITSWAN_DEPLOYMENT_ID: internal-frontend-staging
      BITSWAN_DEPLOY_CHECKSUM: b79a86623d2cb8120f15d30c2f302db2b3c76521
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:56:59.686046Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-staging.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./WingsData s.r.o.
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-staging-client
      OAUTH2_PROXY_CLIENT_SECRET: fJHIpbpPTSLoD5kxZFLDJBiflgmqkNrK
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-stagin-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-staging
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-stagin-staging.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/b79a86623d2cb8120f15d30c2f302db2b3c76521:/app/
  internal-frontend-wt-tim-live-dev:
    container_name: deployment-management__internal-frontend-wt-tim-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /WingsData s.r.o.
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-wt-tim-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: deployment-management-wt-tims-dev-tree-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-wt-tims-dev-tree-deployment-management-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-04-08T22:57:00.143054Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-live-dev.bitswan-devops-1.bswn.io
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /WingsData s.r.o./admin
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-wt-tims-dev-tree-deployment-management-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: wYGSaoMZxALoMDJL5fjaxZnfdOojBJYH
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-wt-tim-live-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      POSTGRES_DB: postgres_wt_tims_dev_tree
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-wt-tims-dev-tree-deployment-management-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-wt-tim-live-dev.bitswan-devops-1.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/workspace/worktrees/tims-dev-tree/deployment-management/internal-frontend:/app/
  minio:
    command: server /data --console-address :9001
    container_name: deployment-management__minio
    env_file:
    - /gitops/secrets/minio
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-data-data:/data
  minio-dev:
    command: server /data --console-address :9001
    container_name: deployment-management__minio-dev
    env_file:
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio-dev.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-dev-data-data:/data
  minio-staging:
    command: server /data --console-address :9001
    container_name: deployment-management__minio-staging
    env_file:
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-minio-staging.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-minio-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-minio-staging-data-data:/data
  postgres:
    container_name: deployment-management__postgres
    env_file:
    - /gitops/secrets/postgres
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-data-data:/var/lib/postgresql/data
  postgres-dev:
    container_name: deployment-management__postgres-dev
    env_file:
    - /gitops/secrets/postgres-dev
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-dev-data-data:/var/lib/postgresql/data
  postgres-dev-pgadmin:
    container_name: deployment-management__postgres-dev-pgadmin
    env_file:
    - /gitops/secrets/postgres-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres-dev.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres-dev.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-pgadmin:
    container_name: deployment-management__postgres-pgadmin
    env_file:
    - /gitops/secrets/postgres
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-staging:
    container_name: deployment-management__postgres-staging
    env_file:
    - /gitops/secrets/postgres-staging
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - deployment-management-postgres-staging-data-data:/var/lib/postgresql/data
  postgres-staging-pgadmin:
    container_name: deployment-management__postgres-staging-pgadmin
    env_file:
    - /gitops/secrets/postgres-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://deployment-management-postgres-staging.bitswan-devops-1.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: U1S53lPsLGJIfaPvpwWWakg5Qd3dko10
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-postgres-staging.bitswan-devops-1.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
version: '3'
volumes:
  deployment-management-minio-data-data: null
  deployment-management-minio-dev-data-data: null
  deployment-management-minio-staging-data-data: null
  deployment-management-postgres-data-data: null
  deployment-management-postgres-dev-data-data: null
  deployment-management-postgres-staging-data-data: null
