networks:
  bitswan_network:
    external: true
services:
  internal-frontend-dev:
    container_name: deployment-management__internal-frontend-dev
    environment:
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://deployment-management-internal-frontend-dev.bitswan-devops-1.bswn.io/
      BITSWAN_DEPLOYMENT_ID: internal-frontend-dev
      BITSWAN_DEPLOY_CHECKSUM: 5f3fed5bfb7efed0aa9d303303e214b6b0fdbd32
      BITSWAN_DEPLOY_TIME: '2026-03-19T17:59:12.415067Z'
      BITSWAN_GITOPS_DOMAIN: bitswan-devops-1.bswn.io/
      BITSWAN_URL_PREFIX: https://deployment-management-
      BITSWAN_URL_SUFFIX: .bitswan-devops-1.bswn.io/
      BITSWAN_URL_TEMPLATE: https://deployment-management-{name}-dev.bitswan-devops-1.bswn.io/
      BITSWAN_WORKSPACE_NAME: deployment-management
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /Example Organization
      OAUTH2_PROXY_CLIENT_ID: workspace-626ae6bc-2874-46ae-9ba1-f86ac959decb-internal-frontend-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: ofofPqh1m7NZMSWMVdV9xJGuhKPBF2nw
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: Tapk4dUWIXxhKkpDabnFrpUPbTP9yPUs
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PATH: /root/.config/bitswan/oauth2-proxy
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://deployment-management-internal-frontend-dev.bitswan-devops-1.bswn.io//oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a
    labels:
      gitops.certs.enabled: 'true'
      gitops.deployment_id: internal-frontend-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.workspace: deployment-management
    networks:
      bitswan_network:
        aliases:
        - deployment-management-internal-frontend-dev.bitswan-devops-1.bswn.io/
    restart: always
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/deployment-management/gitops/5f3fed5bfb7efed0aa9d303303e214b6b0fdbd32:/app/
version: '3'
